# Generated by Django 5.2.10 on 2026-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('RTSP', 'RTSP (Real-Time Streaming Protocol)'), ('HLS', 'HLS (HTTP Live Streaming)'), ('IPWEBCAM', 'IP Webcam')], default='RTSP', max_length=10),
        ),
    ]
